In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 17.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 688 ms
Wall time: 696 ms


In [5]:
# Генерация случайных данных
data = np.random.rand(2,3)
data

array([[0.36966039, 0.02784997, 0.6372057 ],
       [0.58906522, 0.53560582, 0.44572803]])

In [6]:
data * 10

array([[3.69660393, 0.27849975, 6.37205701],
       [5.89065221, 5.35605823, 4.45728028]])

In [7]:
data + data

array([[0.73932079, 0.05569995, 1.2744114 ],
       [1.17813044, 1.07121165, 0.89145606]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [24]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [29]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [37]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [45]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [46]:
arr2d[0][2]

3

In [47]:
arr2d[0, 2]

3

In [48]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[1, 0]

array([7, 8, 9])

In [54]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
x[0]

array([7, 8, 9])

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [59]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [62]:
arr2d[1, :2]

array([4, 5])

In [63]:
arr2d[:2, 2]

array([3, 6])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [65]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [68]:
data

array([[-1.31629772,  0.37385282,  1.72340397, -1.5115836 ],
       [ 0.98926685,  0.88766116,  0.51138093, -0.477296  ],
       [-1.30284368, -0.71806077,  1.19696133,  0.16265443],
       [ 0.85298388, -0.46700557, -1.56270484,  0.44438411],
       [-1.00865274, -0.19755238,  1.5572522 , -0.25225465],
       [ 0.29319908, -0.1889963 , -0.62539842,  1.47856003],
       [-0.5621543 ,  0.50346457,  0.49421087, -0.88390903]])

In [69]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [70]:
data[names == 'Bob']

array([[-1.31629772,  0.37385282,  1.72340397, -1.5115836 ],
       [ 0.85298388, -0.46700557, -1.56270484,  0.44438411]])

In [71]:
data[names == 'Bob', 2:]

array([[ 1.72340397, -1.5115836 ],
       [-1.56270484,  0.44438411]])

In [72]:
data[names == 'Bob', 2]

array([ 1.72340397, -1.56270484])

In [73]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [74]:
data[~(names == 'Bob')]

array([[ 0.98926685,  0.88766116,  0.51138093, -0.477296  ],
       [-1.30284368, -0.71806077,  1.19696133,  0.16265443],
       [-1.00865274, -0.19755238,  1.5572522 , -0.25225465],
       [ 0.29319908, -0.1889963 , -0.62539842,  1.47856003],
       [-0.5621543 ,  0.50346457,  0.49421087, -0.88390903]])

In [75]:
cond = names == 'Bob'
data[~cond]

array([[ 0.98926685,  0.88766116,  0.51138093, -0.477296  ],
       [-1.30284368, -0.71806077,  1.19696133,  0.16265443],
       [-1.00865274, -0.19755238,  1.5572522 , -0.25225465],
       [ 0.29319908, -0.1889963 , -0.62539842,  1.47856003],
       [-0.5621543 ,  0.50346457,  0.49421087, -0.88390903]])

In [76]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [77]:
data[mask]

array([[-1.31629772,  0.37385282,  1.72340397, -1.5115836 ],
       [-1.30284368, -0.71806077,  1.19696133,  0.16265443],
       [ 0.85298388, -0.46700557, -1.56270484,  0.44438411],
       [-1.00865274, -0.19755238,  1.5572522 , -0.25225465]])

In [78]:
data[data < 0] = 0
data

array([[0.        , 0.37385282, 1.72340397, 0.        ],
       [0.98926685, 0.88766116, 0.51138093, 0.        ],
       [0.        , 0.        , 1.19696133, 0.16265443],
       [0.85298388, 0.        , 0.        , 0.44438411],
       [0.        , 0.        , 1.5572522 , 0.        ],
       [0.29319908, 0.        , 0.        , 1.47856003],
       [0.        , 0.50346457, 0.49421087, 0.        ]])

In [79]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.98926685, 0.88766116, 0.51138093, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.29319908, 0.        , 0.        , 1.47856003],
       [0.        , 0.50346457, 0.49421087, 0.        ]])

In [80]:
arr = np.empty((8, 4))
for i in range(8):
 arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [82]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [83]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [85]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.rand(6, 3)
arr

array([[0.94679332, 0.55948624, 0.53974499],
       [0.11594416, 0.58238139, 0.96996646],
       [0.0575213 , 0.69280221, 0.7294842 ],
       [0.81652118, 0.99311694, 0.12649285],
       [0.91076563, 0.00289915, 0.36771818],
       [0.86103731, 0.57536043, 0.5634577 ]])

In [88]:
np.dot(arr.T, arr)

array([[3.15075546, 1.94604069, 1.58879704],
       [1.94604069, 2.44949713, 1.82313809],
       [1.58879704, 1.82313809, 2.23300846]])

In [2]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [3]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [4]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [5]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])