# Универсальные функции

In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)

In [5]:
x

array([ 0.16409949,  0.3244163 ,  0.34183221,  0.37555762, -1.28610916,
        1.80336364,  0.65119628, -1.00649118])

In [6]:
y

array([ 2.16450916, -0.30078772,  0.39414746, -0.10727044,  0.40047987,
       -0.69506867, -0.19779457,  0.17783911])

In [7]:
np.maximum(x, y)

array([2.16450916, 0.3244163 , 0.39414746, 0.37555762, 0.40047987,
       1.80336364, 0.65119628, 0.17783911])

In [8]:
arr = np.random.randn(7) * 5 #нормальное распределение
arr

array([-1.07412949, -0.83102442, -7.21541692,  0.92289634, -3.82951003,
       -2.68540365,  5.79384962])

In [9]:
remaider, whole_part = np.modf(arr) #возвращает целую и дробную части
remaider

array([-0.07412949, -0.83102442, -0.21541692,  0.92289634, -0.82951003,
       -0.68540365,  0.79384962])

In [10]:
whole_part

array([-1., -0., -7.,  0., -3., -2.,  5.])

In [11]:
arr

array([-1.07412949, -0.83102442, -7.21541692,  0.92289634, -3.82951003,
       -2.68540365,  5.79384962])

In [12]:
np.sqrt(arr)

C:\Users\idgar\AppData\Local\Temp\ipykernel_5248\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan, 0.96067494,        nan,
              nan, 2.40704167])

In [13]:
np.sqrt(arr, arr)

C:\Users\idgar\AppData\Local\Temp\ipykernel_5248\269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan,        nan, 0.96067494,        nan,
              nan, 2.40704167])

In [14]:
arr

array([       nan,        nan,        nan, 0.96067494,        nan,
              nan, 2.40704167])

In [19]:
print(np.abs(-25))

25


In [26]:
np.fabs([-10.1, -100])

array([ 10.1, 100. ])

In [24]:
np.abs([-19.1, -2,111])

array([ 19.1,   2. , 111. ])

In [30]:
np.square([-2, 2])

array([4, 4])

In [34]:
np.exp([0, 1, 2])

array([1.        , 2.71828183, 7.3890561 ])

In [38]:
np.log(1)

0.0

In [39]:
np.log10(100)

2.0

In [42]:
np.log2(1024)

10.0

In [55]:
np.log1p(0) # numpy.log1p(x) возвращает натуральный логарифм (x + 1)

0.0

In [63]:
np.sign([10, 0, -11, 0, -5, 10.4]) # вычисляет знак каждого элемента

array([ 1.,  0., -1.,  0., -1.,  1.])

In [67]:
np.ceil([1.23, 2, -1.48, -1.51, 0]) # верхнее округленное значение

array([ 2.,  2., -1., -1.,  0.])

In [68]:
np.floor([1.23, 2, -1.48, -1.51, 0]) # нижнее округленное значение

array([ 1.,  2., -2., -2.,  0.])

In [69]:
np.rint([1.23, 2, -1.48, -1.51, 0]) # ближайшее округленное значение

array([ 1.,  2., -1., -2.,  0.])

In [75]:
np.isnan([1, np.inf, np.nan, -2, 0])

array([False, False,  True, False, False])

In [76]:
np.isfinite([1, np.inf, np.nan, -2, 0])

array([ True, False, False,  True,  True])

In [77]:
np.isinf([1, np.inf, np.nan, -2, 0])

array([False,  True, False, False, False])

In [79]:
np.cosh(0)

1.0

In [81]:
np.cos(np.pi)

-1.0

In [82]:
np.sin(np.pi/2)

1.0

In [85]:
np.sinh(0)

0.0

In [91]:
np.tan(0)

0.0

In [92]:
np.tanh(0)

0.0

In [96]:
np.arccos(-1)

3.141592653589793

In [97]:
np.logical_not(10)

False

In [98]:
np.logical_not(-10)

False

In [99]:
np.logical_not([1, 0, True, False, 5])

array([False,  True, False,  True, False])

In [100]:
np.add([1, 1, 1], [2, 2, 2])

array([3, 3, 3])

In [101]:
np.add(1, [2, 2, 2])

array([3, 3, 3])

In [102]:
np.subtract([1, 1, 1], [2, 2, 2])

array([-1, -1, -1])

In [103]:
np.subtract([1, 1, 1], 10)

array([-9, -9, -9])

In [104]:
np.multiply([2, 2, 2], [2, 2, 2])

array([4, 4, 4])

In [106]:
np.divide([4, 4, 4], [5, 2, 2])

array([0.8, 2. , 2. ])

In [107]:
np.floor_divide([4, 4, 4], [5, 2, 2])

array([0, 2, 2])

In [110]:
np.power([10, 1.6, 4, -100, 0], 2) # элементы первого массива возводятся в степени из второго массива поэлементно

array([1.00e+02, 2.56e+00, 1.60e+01, 1.00e+04, 0.00e+00])

In [112]:
np.maximum([10, 1.6, 4, -100, 0], [1, 2, 0, np.inf, np.nan])

array([10.,  2.,  4., inf, nan])

In [113]:
np.fmax([10, 1.6, 4, -100, 0], [1, 2, 0, np.inf, np.nan])

array([10.,  2.,  4., inf,  0.])

In [114]:
np.minimum([10, 1.6, 4, -100, 0], [1, 2, 0, np.inf, np.nan])

array([   1. ,    1.6,    0. , -100. ,    nan])

In [115]:
np.fmin([10, 1.6, 4, -100, 0], [1, 2, 0, np.inf, np.nan])

array([   1. ,    1.6,    0. , -100. ,    0. ])

In [118]:
np.mod([14, -5, 0], [10, 5, np.inf])

array([4., 0., 0.])

In [119]:
np.copysign([14, -1, -2, 0], [-1, 0, -2, -5])

array([-14.,   1.,  -2.,  -0.])

In [120]:
np.greater([14, 5, 0, np.inf, np.nan], [7, 10, 1, 0, 0]) #сравнивает поэлементно, выражение - (arr1 > arr2)
#для greater_equal, less, less_equal, equal выражения равны (arr1 => arr2), (arr1 < arr2), (arr1 <= arr2), (arr1 == arr2) соотв.

array([ True, False, False,  True, False])

In [122]:
np.logical_and([True, False, 1, 0, 11, -12], [True, True, 0, 5, 4, -0])

array([ True, False, False, False,  True, False])

In [123]:
np.logical_or([True, False, 1, 0, 11, -12], [True, True, 0, 5, 4, -0])

array([ True,  True,  True,  True,  True,  True])

In [124]:
np.logical_xor([True, False, 1, 0, 11, -12], [True, True, 0, 5, 4, -0])

array([False,  True,  True,  True, False,  True])

# Программирование с применением массивов

In [125]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [126]:
result = [(x if c else y) # так делать не надо
for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [127]:
result = np.where(cond, xarr, yarr) # надо так
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [128]:
arr = np.random.randn(4, 4)
arr

array([[ 0.86242069,  0.38915248,  0.62290293, -1.50261915],
       [-1.20614402, -0.17673085,  0.63659238,  0.59770631],
       [ 0.79548266,  0.51622879,  0.28022782,  0.23723427],
       [-0.25972361,  1.19747471,  0.00170578,  0.07368852]])

In [129]:
arr > 0

array([[ True,  True,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [130]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2, -2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2,  2,  2]])

In [131]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ,  2.        , -1.50261915],
       [-1.20614402, -0.17673085,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.25972361,  2.        ,  2.        ,  2.        ]])

# Математические и статистические операции

In [132]:
arr = np.random.randn(5, 4)
arr

array([[-0.40708023,  1.03056955,  0.20858806,  0.1218589 ],
       [-0.66305138, -1.0540958 , -1.15361235,  0.3705339 ],
       [ 0.05903394,  1.37934948,  2.31038342,  0.74751486],
       [ 0.42797619, -0.30330872, -0.25365217, -0.53868817],
       [-0.47581282, -0.29040929,  0.19838912,  0.45557218]])

In [133]:
arr.mean()

0.10850293400409357

In [134]:
np.mean(arr)

0.10850293400409357

In [135]:
arr.sum()

2.1700586800818713

In [136]:
arr.mean(axis=1) # вычисляется статистика по заданной оси,  среднее по строкам

array([ 0.23848407, -0.62505641,  1.12407043, -0.16691822, -0.0280652 ])

In [137]:
arr.sum(axis=0) # сумма по столбцам

array([-1.0589343 ,  0.76210523,  1.31009608,  1.15679167])

In [138]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [139]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [141]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

In [142]:
arr.min()

1

In [143]:
arr.max()

9

In [145]:
arr.std() # стандартное отклонение

2.581988897471611

In [146]:
arr.var() # дисперсия

6.666666666666667

In [147]:
arr.argmax()

8

In [148]:
arr.argmin()

0

# Методы булевых массивов

In [149]:
arr = np.random.randn(100)
(arr > 0).sum() # количество положительных значений

50

In [150]:
bools = np.array([False, False, True, False])
bools.any()

True

In [151]:
bools.all()

False

# Сортировка 

In [152]:
arr = np.random.randn(6)
arr

array([ 0.33181709,  0.34743081, -0.31221871,  0.41507733,  1.10433625,
       -0.74579786])

In [153]:
arr.sort()
arr


array([-0.74579786, -0.31221871,  0.33181709,  0.34743081,  0.41507733,
        1.10433625])

In [154]:
arr = np.random.randn(5, 3)
arr

array([[ 1.05689802, -0.36432277, -3.31062987],
       [ 0.22270133, -0.27793757,  0.44584596],
       [ 0.3942622 ,  0.94437174, -1.30217053],
       [ 0.4826359 ,  1.32855139, -1.02701963],
       [ 2.25321874,  1.33822385,  1.41848839]])

In [155]:
arr.sort(1)
arr

array([[-3.31062987, -0.36432277,  1.05689802],
       [-0.27793757,  0.22270133,  0.44584596],
       [-1.30217053,  0.3942622 ,  0.94437174],
       [-1.02701963,  0.4826359 ,  1.32855139],
       [ 1.33822385,  1.41848839,  2.25321874]])

In [158]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5%ый квантиль, значение, которое заданная случайная величина
                                      # не превышает с фиксированной вероятностью

-1.4574066060057091

# Удаление дубликатов и другие теоретико-множественные операции

In [159]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob',
 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [160]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4 ,4])
np.unique(ints)

array([1, 2, 3, 4])

In [161]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [162]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6]) # np.in1d проверяет наличие значений из одного массива в другом и возвращает булев массив

array([ True, False, False,  True,  True, False,  True])

In [3]:
np.intersect1d([0, 2, 1, -1, np.nan], [0, 1, 10, -5, np.nan, np.inf]) # пересечение массивов

array([0., 1.])

In [4]:
np.union1d([-2, 5, 10, 0], [5, 4, 10, -55, np.nan]) # объединение массивов

array([-55.,  -2.,   0.,   4.,   5.,  10.,  nan])

In [5]:
np.setdiff1d([1, 2, 3, 4, 5, 0], [3, 4, 5, 6, 10, 54]) #уникальные значения в первом множестве

array([0, 1, 2])

In [6]:
np.setxor1d([1, 2, 3, 4], [3, 4, 5, 6]) # не совпадающие значения из двух множеств

array([1, 2, 5, 6])

# Файловый ввод-вывод массивов

In [7]:
arr = np.arange(10)
np.save('some_array', arr)

In [8]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez('array_archive.npz', a=arr, b=arr)

In [10]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [14]:
arch = np.load('arrays_compressed.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Линейная алгебра

In [15]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [17]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [18]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [19]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [20]:
x @ np.ones(3)

array([ 6., 15.])

In [21]:
from numpy.linalg import inv, qr

In [22]:
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 2.69651254,  3.96268402, -2.8486224 , -2.16441924, -0.30567435],
       [ 3.96268402,  6.45549026, -4.58612251, -3.87959448, -0.48842161],
       [-2.8486224 , -4.58612251,  3.4845661 ,  2.82619212,  0.45174663],
       [-2.16441924, -3.87959448,  2.82619212,  3.07573583,  0.34654742],
       [-0.30567435, -0.48842161,  0.45174663,  0.34654742,  0.16341079]])

In [23]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.98006237e-16, -2.57404375e-16,
        -1.02424363e-15, -1.55697489e-16],
       [ 2.82737612e-15,  1.00000000e+00,  1.09655764e-15,
        -7.04947230e-16, -1.23444733e-16],
       [-1.09239132e-15,  4.06656078e-16,  1.00000000e+00,
        -2.76780268e-15,  3.34011298e-16],
       [-1.82022372e-16, -1.04871508e-15,  7.26567770e-16,
         1.00000000e+00,  5.74558920e-17],
       [-2.70365648e-15, -2.23423626e-15,  1.10155188e-15,
         2.56978061e-15,  1.00000000e+00]])

In [24]:
q, r = qr(mat)
r

array([[ -6.64701221,   4.93057158,  -1.28548419,   2.78881644,
          0.14082886],
       [  0.        ,  -6.62561097, -10.22611848,  -0.38460806,
         12.4545917 ],
       [  0.        ,   0.        ,  -1.41665291,   1.07144488,
          4.12831522],
       [  0.        ,   0.        ,   0.        ,  -0.86430755,
          6.27249453],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.21013091]])

# Генерация псевдо-случайных чисел

In [25]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.33724679,  0.33469136,  0.2524873 ,  1.3201034 ],
       [ 0.03182524,  0.79326609,  1.70678555, -0.3684748 ],
       [-1.00587527,  0.22198459, -0.91924266, -0.88214647],
       [ 0.65140816, -0.83700519, -1.09626512, -0.201264  ]])

In [26]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

600 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%timeit np.random.normal(size=N)

21.2 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
np.random.seed(1234)

In [29]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])