In [5]:
import pandas as pd

In [6]:
from pandas import Series, DataFrame

# Объект Series

In [7]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [13]:
obj2['d'] = 6

In [14]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [17]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4) #Для распознавания отсутствующих данных в pandas следует использовать функции isnull и notnull

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # Индекс объекта Series можно изменить на месте с помощью присваивания
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# Объект DataFrame

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [35]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [37]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [38]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
 index=['one', 'two', 'three', 'four',
 'five', 'six'])

In [39]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [45]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [46]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [47]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [48]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [51]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [52]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [53]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [54]:
pdata = {'Ohio': frame3['Ohio'][:-1],
 'Nevada':frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [55]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [56]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [57]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# Задание 1

### двумерный ndarray:

In [58]:
data_1 = np.array([[1.3, 2.4],[0.3, 4.1]])
frame_1 = pd.DataFrame(data_1)
frame_1

0    1
0  1.3  2.4
1  0.3  4.1

### словарь списков:

In [59]:
data_2 = {2015: ['true', 1, 0.75],
          2016: ['false', 4, 5.55],
          2017: ['true', 3, 4.87]}
frame_2 = pd.DataFrame(data_2, index = ['a', 'b', 'c'])
frame_2

2015   2016  2017
a  true  false  true
b     1      4     3
c  0.75   5.55  4.87

### структурированный массив NumPy: 

In [60]:
data_3 = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)], dtype=('int16, a6, float32, complex64'))
frame_3 = pd.DataFrame(data_3)
frame_3

f0         f1   f2        f3
0   1   b'First'  0.5  1.0+2.0j
1   2  b'Second'  1.3  2.0-2.0j
2   3   b'Third'  0.8  1.0+3.0j

### словарь объектов Series:

In [61]:
data_4 = {1: Series([1, 0, 4, -1.5]),
          2: Series([6, -5.5, 3, 0])}
frame_4 = pd.DataFrame(data_4)
frame_4

1    2
0  1.0  6.0
1  0.0 -5.5
2  4.0  3.0
3 -1.5  0.0

### словарь словарей:

In [62]:
data_5 = {'first': {1: 'Russia', 2: 'China', 3: 'India'},
          'second': {1: 'USA', 2: 'UK', 3: 'Canada'}}
frame_5 = pd.DataFrame(data_5)
frame_5

first  second
1  Russia     USA
2   China      UK
3   India  Canada

### список словарей: 

In [68]:
data_6 = [{1: ['Mary', 'Tom', 'Kim'], 2: ['Jerry', 'Tommy', 'Joe'] }, {1: ['Henry', 'Alex', 'John'], 2: ['Ivan', 'Kate', 'Vito']}]
frame_6 = pd.DataFrame(data_6)
frame_6

1                    2
0     [Mary, Tom, Kim]  [Jerry, Tommy, Joe]
1  [Henry, Alex, John]   [Ivan, Kate, Vito]

### список списков: 

In [69]:
data_7 = [['Mary', 'Tom', 'Kim'], ['Jerry', 'Tommy', 'Joe'], ['Henry', 'Alex', 'John']]
frame_7 = pd.DataFrame(data_7)
frame_7

0      1     2
0   Mary    Tom   Kim
1  Jerry  Tommy   Joe
2  Henry   Alex  John

###  другой объект DataFrame:

In [70]:
data_8 = pd.DataFrame([['Mary', 'Tom', 'Kim'], ['Jerry', 'Tommy', 'Joe']])
frame_8 = pd.DataFrame(data_8)
frame_8

0      1    2
0   Mary    Tom  Kim
1  Jerry  Tommy  Joe

###  MaskedArray:

In [75]:
import numpy.ma as ma
data_9 = ma.array([1, 2, 3], mask = [0, 1, 0])
frame_9 = pd.DataFrame(data_9)
frame_9

0
0  1.0
1  NaN
2  3.0

# Индексные объекты

In [63]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [64]:
index[1:]

Index(['b', 'c'], dtype='object')

In [65]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
2003 in frame2.index

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

# Задание 2

index.append - соединяет вместе коллекции индексов

In [77]:
idx_1 = pd.Index([1, 2, 3])
idx_11 = idx_1.append(pd.Index([4, 5]))
idx_11

Int64Index([1, 2, 3, 4, 5], dtype='int64')

index.difference - возвращает новую коллекцию индексов с элементами, которых нет в другой.

In [78]:
idx_2 = pd.Index([2, 1, 3, 4])
idx_22 = pd.Index([3, 4, 5, 6])
idx_2.difference(idx_22)

Int64Index([1, 2], dtype='int64')

index.intersection - возвращает новый индекс, состоящий из пересечений двух индексов

In [79]:
idx_3 = pd.Index([1, 2, 3, 4])
idx_33 = pd.Index([3, 4, 5, 6])
idx_3.intersection(idx_33)

Int64Index([3, 4], dtype='int64')

index.union - объединение двух индексов (возвращается новый)

In [80]:
idx_4 = pd.Index([1, 2, 3, 4])
idx_44 = pd.Index([3, 4, 5, 6])
idx_4.union(idx_44)

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

index.isin - возвращает новый индекс из булевых значений; определяет вхождение элементов первого индекса во второй

In [82]:
idx = pd.Index([1,2,3])
idx.isin([1, 3])

array([ True, False,  True])

index.delete - удаление элементов индекса на указанных позициях

In [85]:
idx2 = pd.Index(['a', 'b', 'c'])
idx2.delete([1, 2])

Index(['a'], dtype='object')

index.drop - удаление списка индексов из исходного

In [86]:
idx3 = pd.Index(['a', 'b', 'c'])
idx3.drop(['a', 'b'])

Index(['c'], dtype='object')

index.insert - вставка списка индексов

In [88]:
idx4 = pd.Index(['a', 'b', 'c'])
idx4.insert(3, ['a', 'e'])

Index(['a', 'b', 'c', 'a', 'e'], dtype='object')

index.is_monotonic_increasing - возвращает true, если значения равны или увеличиваются, иначе false

In [93]:
pd.Index([1, 2, 3]).is_monotonic_increasing

True

In [94]:
pd.Index([1, 3, 2]).is_monotonic_increasing

False

index.is_unique - true, если индекс имеет уникальные значения, иначе false

In [95]:
pd.Index([1, 5, 7, 7]).is_unique

False

In [96]:
pd.Index([1, 5, 7]).is_unique

True

index.unique - возвращает уникальные значения индекса

In [97]:
pd.Index([1, 1, 2, 3, 3]).unique()

Int64Index([1, 2, 3], dtype='int64')